cc	=g++

all: one two three

one:	counter.cpp
		$(cc) -o counter counter.cpp
two:	pattern.cpp
		$(cc) -o pattern pattern.cpp
three:	convert.cpp
		$(cc) -o convert convert.cpp
clean:;	rm -f  one two three
